export const DaraIpcCommand = {
  AdoptLegacyZoom: 'adopt_legacy_zoom',
  ChangeOffsiteBackupTarget: 'change_offsite_backup_target',
  CreateCardContent: 'create_card_content',
  CreateOffsiteBackupNow: 'create_offsite_backup_now',
  DeleteCardContent: 'delete_card_content',
  DiscoverRemoteBackups: 'discover_remote_backups',
  DisableOffsiteBackup: 'disable_offsite_backup',
  DismissQuickAdd: 'dismiss_quick_add',
  GetSpikeStatus: 'get_spike_status',
  IngestClipboardImage: 'ingest_clipboard_image',
  IngestImageBytes: 'ingest_image_bytes',
  InstallSchedulerReplay: 'install_scheduler_replay',
  LoadCardContent: 'load_card_content',
  LoadApplicationLaunchContext: 'load_application_launch_context',
  LoadDiagnostics: 'load_diagnostics',
  LoadHomeStats: 'load_home_stats',
  LoadOffsiteBackupStatus: 'load_offsite_backup_status',
  LoadRestoredOffsiteBackupTakeoverRequired:
    'load_restored_offsite_backup_takeover_required',
  LoadReviewContext: 'load_review_context',
  LoadSchedulerReplaySnapshot: 'load_scheduler_replay_snapshot',
  LoadSettings: 'load_settings',
  MaintainMedia: 'maintain_media',
  MaintainSearch: 'maintain_search',
  OpenExternalUrl: 'open_external_url',
  PrepareDesiredRetentionReplay: 'prepare_desired_retention_replay',
  RecordGrade: 'record_grade',
  RemoveOffsiteBackupCredentials: 'remove_offsite_backup_credentials',
  ReplaceOffsiteBackupCredentials: 'replace_offsite_backup_credentials',
  RenewMediaLease: 'renew_media_lease',
  SearchCardContent: 'search_card_content',
  SearchStatus: 'search_status',
  SelectNextReviewCard: 'select_next_review_card',
  SetAppearance: 'set_appearance',
  SetCardContentSuspended: 'set_card_content_suspended',
  SetKeyboardBindings: 'set_keyboard_bindings',
  SetLaunchAtLogin: 'set_launch_at_login',
  SetQuickAddFileDialogOpen: 'set_quick_add_file_dialog_open',
  SetZoomPercent: 'set_zoom_percent',
  StartFreshInstall: 'start_fresh_install',
  ShowMain: 'show_main',
  ShowQuickAdd: 'show_quick_add',
  RunOffsiteRestoreDrill: 'run_offsite_restore_drill',
  TakeOverRestoredOffsiteBackup: 'take_over_restored_offsite_backup',
  TestAndEnableOffsiteBackup: 'test_and_enable_offsite_backup',
  UndoLastGrade: 'undo_last_grade',
  UpdateCardContent: 'update_card_content',
} as const

export type DaraIpcCommand =
  (typeof DaraIpcCommand)[keyof typeof DaraIpcCommand]

export const DaraEvent = {
  BrowseCommand: 'browse-command',
  CardCreated: 'card-created',
  OffsiteBackupProgress: 'offsite-backup-progress',
  OpenHome: 'open-home',
  OpenSettings: 'open-settings',
  QuickAddShown: 'quick-add-shown',
  ReviewClockRefresh: 'review-clock-refresh',
  SettingsChanged: 'settings-changed',
  ZoomCommand: 'app-zoom-command',
} as const

export type DaraEvent = (typeof DaraEvent)[keyof typeof DaraEvent]
